workflows:
  ios-release:
    name: Secure Link – iOS Release

    integrations:
      app_store_connect: "secure-link"

    environment:
      vars:
        APP_APPLE_ID: "6752566816"
        XCODE_SCHEME: "secure-link"
        XCODE_PROJECT: "secure-link.xcodeproj"
        BUNDLE_ID: "com.aesthetics.securelink"

      ios_signing:
        provisioning_profiles:
          - AppstoreProd
        certificates:
          - appstore

    scripts:
      - name: Set up code signing
        script: xcode-project use-profiles

      - name: Bump CFBundleVersion (latest+1)
        script: |
          set -euo pipefail
          echo "Fetching latest build number for $APP_APPLE_ID"
          LATEST=$(app-store-connect get-latest-app-store-build-number "$APP_APPLE_ID" || echo 0)
          NEXT=$(( LATEST + 1 ))
          echo "ASC latest: $LATEST -> NEXT: $NEXT"

          # Находим правильный Info.plist по схеме
          SETTINGS=$(xcodebuild -project "$XCODE_PROJECT" -scheme "$XCODE_SCHEME" -showBuildSettings)
          PLIST_PATH=$(echo "$SETTINGS" | awk -F'= ' '/INFOPLIST_FILE/ {print $2; exit}')
          [[ "$PLIST_PATH" != /* ]] && PLIST_PATH="$(pwd)/$PLIST_PATH"
          echo "Main Info.plist: $PLIST_PATH"

          /usr/libexec/PlistBuddy -c "Set :CFBundleVersion $NEXT" "$PLIST_PATH" || \
          /usr/libexec/PlistBuddy -c "Add :CFBundleVersion string $NEXT" "$PLIST_PATH"

          echo "CFBundleVersion now:"
          /usr/libexec/PlistBuddy -c "Print :CFBundleVersion" "$PLIST_PATH"

      - name: Clean & Archive
        script: |
          set -euo pipefail
          xcodebuild clean -project "$XCODE_PROJECT" -scheme "$XCODE_SCHEME" -configuration Release

          set -o pipefail && xcodebuild archive \
            -project "$XCODE_PROJECT" \
            -scheme "$XCODE_SCHEME" \
            -sdk iphoneos \
            -configuration Release \
            -archivePath "$HOME/build/$XCODE_SCHEME.xcarchive" \
            -allowProvisioningUpdates \
          | tee "$CM_BUILD_DIR/xcodebuild.log"

          echo "Archive CFBundleVersion:"
          /usr/libexec/PlistBuddy -c "Print :ApplicationProperties:CFBundleVersion" \
            "$HOME/build/$XCODE_SCHEME.xcarchive/Info.plist" || true

      - name: Export IPA
        script: |
          set -euo pipefail
          xcode-project build-ipa \
            --project "$XCODE_PROJECT" \
            --scheme "$XCODE_SCHEME" \
          | tee "$CM_BUILD_DIR/export.log"

          echo "IPA CFBundleVersion:"
          unzip -p build/ios/ipa/*.ipa "Payload/*.app/Info.plist" | plutil -p - | grep CFBundleVersion
          unzip -p build/ios/ipa/*.ipa "Payload/*.app/Info.plist" | plutil -p - | grep CFBundleShortVersionString || true

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        submit_to_app_store: true
