workflows:
  ios-test-sign:
    name: Minimal iOS Sign & Upload

    integrations:
      app_store_connect: "secure-link"

    environment:
      vars:
        APP_APPLE_ID: "6752566816"
        XCODE_SCHEME: "secure-link"
        BUNDLE_ID: "com.aesthetics.securelink"

      ios_signing:
        provisioning_profiles:
          - AppstoreProd
        certificates:
          - appstore

    scripts:
      - name: Set up code signing in project
        script: xcode-project use-profiles

      - name: Get the latest build number and increment (AGV)
        script: |
          set -euo pipefail
          echo "Fetching latest build number for App ID: $APP_APPLE_ID"
          LATEST=$(app-store-connect get-latest-app-store-build-number "$APP_APPLE_ID" || echo 0)
          NEXT=$(( LATEST + 1 ))
          echo "ASC latest: $LATEST -> NEXT: $NEXT"

          # ВАЖНО: запускаем agvtool в том же каталоге, откуда будем собирать (без cd ios)
          agvtool new-version -all "$NEXT"
          echo "AGV status:"
          agvtool what-version || true
          agvtool what-marketing-version || true

      - name: Clean and archive project
        script: |
          set -euo pipefail
          xcodebuild clean \
            -project "$XCODE_PROJECT" \
            -scheme "$XCODE_SCHEME" \
            -configuration Release

          set -o pipefail && xcodebuild archive \
            -project "$XCODE_PROJECT" \
            -scheme "$XCODE_SCHEME" \
            -sdk iphoneos \
            -configuration Release \
            -archivePath "$HOME/build/$XCODE_SCHEME.xcarchive" \
            -allowProvisioningUpdates \
          | tee "$CM_BUILD_DIR/xcodebuild.log"

          echo "Archive CFBundleVersion:"
          /usr/libexec/PlistBuddy -c "Print :ApplicationProperties:CFBundleVersion" \
            "$HOME/build/$XCODE_SCHEME.xcarchive/Info.plist" || true

      - name: Export .ipa using default settings
        script: |
          set -euo pipefail
          xcode-project build-ipa \
            --project "$XCODE_PROJECT" \
            --scheme "$XCODE_SCHEME" \
          | tee "$CM_BUILD_DIR/export.log"

          echo "IPA CFBundleVersion:"
          unzip -p build/ios/ipa/*.ipa "Payload/*.app/Info.plist" | plutil -p - | grep CFBundleVersion
          unzip -p build/ios/ipa/*.ipa "Payload/*.app/Info.plist" | plutil -p - | grep CFBundleShortVersionString || true

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        submit_to_app_store: true

