workflows:
  ios-test-sign:
    name: Minimal iOS Sign & Upload

    integrations:
      app_store_connect: "secure-link"

    environment:
      vars:
        APP_APPLE_ID: "6752566816"
        XCODE_SCHEME: "secure-link"
        XCODE_PROJECT: "secure-link.xcodeproj"
        BUNDLE_ID: "com.aesthetics.securelink"

      ios_signing:
        provisioning_profiles:
          - AppstoreProd
        certificates:
          - appstore

    scripts:
      - name: Set up code signing in project
        script: xcode-project use-profiles

      - name: Get the latest build number and increment (AGV)
        script: |
          set -euo pipefail
          echo "Fetching latest build number for App ID: $APP_APPLE_ID"
          LATEST=$(app-store-connect get-latest-app-store-build-number "$APP_APPLE_ID" || echo 0)
          NEXT=$(( LATEST + 1 ))
          echo "ASC latest: $LATEST -> NEXT: $NEXT"

          agvtool new-version -all "$NEXT" || true
          echo "AGV status:"
          agvtool what-version || true
          agvtool what-marketing-version || true

      - name: Clean and archive project
        script: |
          set -euo pipefail

          # Автовыбор -workspace / -project
          if [[ -n "${XCODE_WORKSPACE:-}" ]]; then
            BUILD_ARGS=(-workspace "$XCODE_WORKSPACE" -scheme "$XCODE_SCHEME")
          else
            BUILD_ARGS=(-project "${XCODE_PROJECT:?Set XCODE_PROJECT or XCODE_WORKSPACE}" -scheme "$XCODE_SCHEME")
          fi

          xcodebuild clean \
            "${BUILD_ARGS[@]}" \
            -configuration Release

          set -o pipefail && xcodebuild archive \
            "${BUILD_ARGS[@]}" \
            -sdk iphoneos \
            -configuration Release \
            -archivePath "$HOME/build/$XCODE_SCHEME.xcarchive" \
            -allowProvisioningUpdates \
          | tee "$CM_BUILD_DIR/xcodebuild.log"

          echo "Archive CFBundleVersion:"
          /usr/libexec/PlistBuddy -c "Print :ApplicationProperties:CFBundleVersion" \
            "$HOME/build/$XCODE_SCHEME.xcarchive/Info.plist" || true

      - name: Export .ipa using default settings
        script: |
          set -euo pipefail
          if [[ -n "${XCODE_WORKSPACE:-}" ]]; then
            xcode-project build-ipa --workspace "$XCODE_WORKSPACE" --scheme "$XCODE_SCHEME" \
            | tee "$CM_BUILD_DIR/export.log"
          else
            xcode-project build-ipa --project "$XCODE_PROJECT" --scheme "$XCODE_SCHEME" \
            | tee "$CM_BUILD_DIR/export.log"
          fi

          echo "IPA CFBundleVersion:"
          unzip -p build/ios/ipa/*.ipa "Payload/*.app/Info.plist" | plutil -p - | grep CFBundleVersion
          unzip -p build/ios/ipa/*.ipa "Payload/*.app/Info.plist" | plutil -p - | grep CFBundleShortVersionString || true

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        submit_to_app_store: true

